/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  
  rocketSidebar: [
    {
      type: 'category',
      label: 'Falcon 9',
      items: ['rockets/falcon-9/falcon-9'],
    },
    {
      type: 'category',
      label: 'Falcon Heavy',
      items: ['rockets/falcon-heavy/falcon-heavy'],
    },
    {
      type: 'category',
      label: 'Starship',
      items: ['rockets/starship/starship'],
    },
  ],

  engineSidebar: [
    {
      type: 'category',
      label: 'Raptor',
      items: ['engines/raptor/raptor'],
    },
    {
      type: 'category',
      label: 'Merlin',
      items: ['engines/merlin/merlin'],
    },
  ],

  projectSidebar: [
    {
      type: 'category',
      label: 'Dragon',
      items: ['projects/dragon/dragon'],
    },
    {
      type: 'category',
      label: 'Starlink',
      items: ['projects/starlink/starlink'],
    },
  ],
  
  launchesSidebar: [
    {
      type: 'category',
      label: 'Launches',
      items: ['launches/launches'],
    },

  ],
};

export default sidebars;
